//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_İle_Döviz_Kuru_Cekme.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ConsoledbProjeEntities : DbContext
    {
        public ConsoledbProjeEntities()
            : base("name=ConsoledbProjeEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Tablocurrency> Tablocurrency { get; set; }
        public virtual DbSet<Tablocurrencyvalues> Tablocurrencyvalues { get; set; }
        public virtual DbSet<Tabloislem> Tabloislem { get; set; }
    }
}
