//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_İle_Döviz_Kuru_Cekme.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablocurrencyvalues
    {
        public int ID { get; set; }
        public Nullable<int> kurID { get; set; }
        public Nullable<decimal> kuralisfiyat { get; set; }
        public Nullable<decimal> kursatisfiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Tablocurrency Tablocurrency { get; set; }
    }
}
